version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps"
    allow:
      - dependency-name: "homeassistant"
      - dependency-name: "pytest"
      - dependency-name: "pytest-asyncio"
      - dependency-name: "mkdocs*"
      - dependency-name: "ruff"
